package forminput;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author muham
 */
public final class Forminputpengembalian extends javax.swing.JFrame {

    Connection conn = koneksi.koneksidatabase.Konek();
    Statement st;
    ResultSet rs;
    String sql;
    DefaultTableModel dtm;
    
    private DefaultTableModel model;
    
    public Forminputpengembalian() {
        initComponents();
        LoadDataPeminjaman();
        TampilDataPeminjamanPadaTabel();
    }
    
    void KosongkanObjek(){
        nomoranggota.setText("");
        kodebuku.setText("");
        tglpinjam.setText("");
        tglkembali.setDate(null);
        denda.setText("");
        combopinjam.setSelectedItem("");
    }
    
    public void LoadDataPeminjaman() {
        String kd="";
        try{
            
            st = conn.createStatement();
            sql = "select * from peminjaman_buku";
            rs = st.executeQuery(sql);

            while (rs.next()) {
                combopinjam.addItem(rs.getString("kode_pinjam"));
            }
            
        } catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }
    
    
    private void AturJTable(JTable Lihat, int Lebar[]){
        try{
            Lihat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            int banyak = Lihat.getColumnCount(); 
            for (int i = 0; i < banyak; i++) {
                TableColumn Kolom = Lihat.getColumnModel().getColumn(i);
                Kolom.setPreferredWidth(Lebar[i]);
                Lihat.setRowHeight(20);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah"+e);
        } 
    }
    
    private void TampilModelJTabel(){
        try {
            String[]kolom={"Kode Pinjam","Status", "Nomor Anggota","Nama Buku","Tanggal Peminjaman",
            "Tanggal Pengembalian", "Denda"};
            dtm = new DefaultTableModel(null, kolom){
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };
            tabel.setModel(dtm);
            AturJTable(tabel, new int []{100,100,100,200,150,150,90} );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah"+e);
        }
    }
    
    void TampilDataPeminjamanPadaTabel() {
    try {
        
        st = conn.createStatement();
        TampilModelJTabel();

        try {
            sql = "SELECT peminjaman_buku.*, buku.judul AS nama_buku FROM peminjaman_buku INNER JOIN buku ON peminjaman_buku.kode_buku = buku.kode;";
            rs = st.executeQuery(sql);

            while (rs.next()) {
                dtm.addRow(new Object[]{
                        rs.getString("kode_pinjam"),
                        rs.getString("status"),
                        rs.getString("nomor_anggota"),
                        rs.getString("nama_buku"),
                        rs.getString("tanggal_peminjaman"),
                        rs.getString("tanggal_pengembalian"),
                        rs.getString("denda"),
                });
                tabel.setModel(dtm); 
            }

            // Pindahkan tabel.setModel(dtm) ke luar loop while

        } catch (SQLException e) {
            System.out.println("Ada Kesalahan " + e.toString());
        }

    } catch (SQLException e) {
        System.out.println("koneksi gagal " + e.toString());
    } finally {
        try {
            if (rs != null) rs.close();
            if (st != null) st.close();
        } catch (SQLException ex) {
            System.out.println("Tutup Statement atau ResultSet Gagal " + ex.toString());
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomoranggota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kodebuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        combopinjam = new javax.swing.JComboBox<>();
        tglpinjam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        denda = new javax.swing.JTextField();
        tglkembali = new com.toedter.calendar.JDateChooser();

        jButton2.setText("EXIT");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM PENGEMBALIAN BUKU");

        jLabel3.setText("NOMOR ANGGOTA");

        jLabel2.setText("KODE BUKU");

        jLabel4.setText("TANGGAL PEMINJAMAN");

        jLabel5.setText("TANGGAL PENGEMBALIAN");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("KODE PINJAM");

        combopinjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        combopinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopinjamActionPerformed(evt);
            }
        });

        tglpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglpinjamActionPerformed(evt);
            }
        });

        jLabel6.setText("DENDA");

        tglkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglkembaliPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tglpinjam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kodebuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomoranggota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combopinjam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(denda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglkembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combopinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomoranggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(denda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(jButton1))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int baris = tabel.rowAtPoint (evt.getPoint());

        String kode_pinjam = tabel.getValueAt(baris, 0).toString();
        combopinjam.setSelectedItem(kode_pinjam);
        
        String no_anggota = tabel.getValueAt(baris, 2).toString();
        nomoranggota.setText(no_anggota);
        
        String kd_buku = tabel.getValueAt(baris, 3).toString();
        kodebuku.setText(kd_buku);
        
        String tgllpinjam = tabel.getValueAt(baris, 4).toString();
        tglpinjam.setText(tgllpinjam);

        Object tgllkembaliObject = tabel.getValueAt(baris, 5).toString();
            
        try {
            Date tanggalKembali;
            tanggalKembali = (tgllkembaliObject instanceof Date) ?
                    (Date) tgllkembaliObject :
                    new SimpleDateFormat("yyyy-MM-dd").parse(tgllkembaliObject.toString());
            tglkembali.setDate(tanggalKembali);
        } catch (ParseException ex) {
            Logger.getLogger(formAnggotaPerpus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String dendanya = tabel.getValueAt(baris, 6).toString();
        denda.setText(dendanya);
    }//GEN-LAST:event_tabelMouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String Tampilan = "yyyy-MM-dd";
        SimpleDateFormat Fm = new SimpleDateFormat(Tampilan);
        String tgllkembali = String.valueOf(Fm.format(tglkembali.getDate()));

        try {
            
            st = null;
            sql = "update peminjaman_buku set tanggal_pengembalian = '" + tgllkembali + "', denda = '" + denda.getText() +"', status = '" + "Dikembalikan" + "',"  + "last_update = NOW(), userid = 'ADMIN' where kode_pinjam = '" + combopinjam.getSelectedItem() + "' ";

            st = conn.createStatement();
            int AdaPerubahanRecord = st.executeUpdate(sql);

            TampilDataPeminjamanPadaTabel();

            if (AdaPerubahanRecord > 0) {
                JOptionPane.showMessageDialog(this, "Buku Telah Dikembalikan", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                denda.setText(null);
                combopinjam.setSelectedIndex(0);
                tglkembali.setDate(null);
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Di Edit", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            st.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combopinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopinjamActionPerformed
        // TODO add your handling code here:
        String Kode="";
        String Kode1="";
        String Kode2="";
        String Kode3="";
        try{
            
            st = conn.createStatement();
            sql = "select * from peminjaman_buku where kode_pinjam='" +combopinjam.getSelectedItem().toString()+"'";
            rs = st.executeQuery(sql);

            while(rs.next()) {
                Kode = rs.getString("nomor_anggota");
                Kode1 = rs.getString("kode_buku");
                Kode2 = rs.getString("tanggal_peminjaman");
                Kode3 = rs.getString("tanggal_pengembalian");
            }
            nomoranggota.setText(Kode);
            kodebuku.setText(Kode1);
            tglpinjam.setText(Kode2);

        } catch(SQLException e){
            System.out.println("koneksi gagal"+e.toString());
        }
        
    }//GEN-LAST:event_combopinjamActionPerformed

    private void tglpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamActionPerformed
private LocalDate convertJDateChooserToLocalDate(Date date) {
        return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    private void tglkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglkembaliPropertyChange
        // TODO add your handling code here:
        try{
                st = conn.createStatement();
                sql = "SELECT tanggal_peminjaman FROM peminjaman_buku WHERE kode_pinjam = '"+combopinjam.getSelectedItem()+"'";
                rs = st.executeQuery(sql);

                if (rs.next()) {
                    LocalDate tanggalPeminjaman = rs.getDate("tanggal_peminjaman").toLocalDate(); // Konversi dari SQL Date ke LocalDate
                    LocalDate tanggalPengembalian = convertJDateChooserToLocalDate(tglkembali.getDate());

                    long selisihHari = ChronoUnit.DAYS.between(tanggalPeminjaman, tanggalPengembalian);


                    if (selisihHari >= 7) {
                        int biayaKeterlambatan = 2000;
                        int totalBiaya = (int) ((selisihHari - 7) * biayaKeterlambatan);
                        
                        denda.setText(String.valueOf(totalBiaya));                     
                    } else {
                        denda.setText("0");
                    }
                } else {
                    // Handle jika tidak ada data peminjaman dengan id yang sesuai
                    //System.out.println("Data peminjaman tidak ditemukan.");
                }
            }catch (SQLException e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_tglkembaliPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forminputpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forminputpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forminputpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forminputpengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forminputpengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> combopinjam;
    private javax.swing.JTextField denda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodebuku;
    private javax.swing.JTextField nomoranggota;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tglkembali;
    private javax.swing.JTextField tglpinjam;
    // End of variables declaration//GEN-END:variables
}
